### ISSUE TITLE
Release 1.7.1

### ISSUE THREAD

**Issue by 40b0a3cd** [NLnetLabs/ldns#10]
It looks like ed25519 support was added nearly 2 years ago. Are there any plans to release it anytime soon?

I'm specifically using ldns-signzone, and would really like to replace some of my SHA1-based signatures.

Thanks!

**Comment by wtoorop** [comment]
I agree, a release is long overdue.  I'll try to make a release planning...

**Comment by noloader** [comment]
Please consider clearing [Issue #8](https://github.com/NLnetLabs/ldns/issues/8) and [Issue #13](https://github.com/NLnetLabs/ldns/issues/13) before releasing 1.7.1. We need something to verify the build in the field. I think it is especially important since OpenSSH is using ldns for DNSSEC.
