### ISSUE TITLE
host2str.h str2host.h docs missing param[out] annotations

### ISSUE THREAD

**Issue by aldot** [NLnetLabs/ldns#149]
Hi!

small doc glitch i thought i could mention..
Ok:
`$ git grep -c "\[out" ldns/host2wire.h`
ldns/host2wire.h:21

Not so:
`$ git grep -c "\[out" ldns/{str2host,host2str}.h`
$
and hence too many [in]
`$ git grep -c "\[in" ldns/{str2host,host2str}.h`
ldns/host2str.h:154
ldns/str2host.h:74

I didn't look at other files.
thanks,

**Comment by aldot** [comment]
`sed -i -e 's/param\[in] rd/param[out] rd/' ldns/str2host.h`

or, more generally

`find * -name "*.h" -exec sed -i -e '/param\[in] .* put /s/param\[in]/param[out]/' {} \+`

for starters

**Comment by wtoorop** [comment]
Thanks.
I have addressed the annotation of returning values via parameters at least for constructors in commit c01ce34
I noticed a few more inconsistencies, but will leave them for now as they involve style and not actual semantics.
