### ISSUE TITLE
drill (1.7.0) fails to support use of both -T and -x options together

### ISSUE THREAD

**Issue by ronbaby** [NLnetLabs/ldns#17]
The subject line says it all.  It appears that the drill command, unlike its BIND counterpart (dig) fails to support the use of the -T and -x options together.  The resulting output, if this is attempted, does not actually show a trace.

In contrast, BIND dig supports the use of its +trace and -x options together in one command and then produces expected output.

Relevant version information is as follows:
     drill version 1.7.0 (ldns version 1.7.0)

**Comment by wtoorop** [comment]
Thanks Ronals,

Issue is resolver on the develop branch, which we intend to turn into a release shortly
