### ISSUE TITLE
Enabling debug output of LDNS

### ISSUE THREAD

**Issue by Zero3K** [NLnetLabs/ldns#208]
How do I do that?

**Comment by wtoorop** [comment]
Most functions return a status of type [ldns_status](https://nlnetlabs.nl/documentation/ldns/error_8h.html#aaa6d98f86f535cf87b83b89e91f488f9). You can convert those values to string with [ldns_get_errorstr_by_id](https://nlnetlabs.nl/documentation/ldns/error_8h.html#a4005bb78082a40de485f947470fa5017)
