### ISSUE TITLE
python3 bindings: ldnsx.py "class resolver" broken

### ISSUE THREAD

**Issue by dogo42** [NLnetLabs/ldns#229]
Hello,

<pre>
  >>> import ldnsx
  >>> ldnsx.resolver("9.9.9.9").query("www.hole.fi", "A")
  Traceback (most recent call last):
  File "", line 1, in
  File "/usr/lib64/python3.9/site-packages/ldnsx.py", line 220, in init
  nm_list.reverse()
  AttributeError: 'filter' object has no attribute 'reverse'
</pre>

There's PR https://github.com/NLnetLabs/ldns/pull/228 that resolves this issue.

**Comment by micwoj92** [comment]
This issue should be closed now.

**Comment by wtoorop** [comment]
Merged PR #228 so closing the Issue.
