### ISSUE TITLE
windows binary of drill?

### ISSUE THREAD

**Issue by cakruege** [NLnetLabs/ldns#234]
Hi,

has anyone tried to compile a windows binary of drill (ideally a static version).
I'm failing with mingw during configure because ssl is missing.
mingw provides only openssl 3 and openssl 1 seems to be needed

greetings
Carsten

**Comment by wcawijngaards** [comment]
There is a compile from 2011, here https://nlnetlabs.nl/~wouter/ldns-1.7.1.zip for version 1.7.1. Also a 32bit version and snapshot compile there.

**Comment by wcawijngaards** [comment]
With the latest commits, the code repository at version https://github.com/NLnetLabs/ldns/commit/073c30f4fda112dfde5c42658afc421de3986305 can compile a windows binary with OpenSSL 3.2. There is a compile of that snapshot of the code repository, here, https://nlnetlabs.nl/~wouter/ldns-1.8.3_20240130.zip .

**Comment by wcawijngaards** [comment]
And another change to the file with the snapshot of 1.8.3, now for commit https://github.com/NLnetLabs/ldns/commit/69738df1c091aa02127cdb6da1d3a6b04a7d8735 . This makes it include the libldns.dll and ldns-config parameters, and some other dll information.

**Comment by cakruege** [comment]
Thank you very much!
