### ISSUE TITLE
Release 1.8.4?

### ISSUE THREAD

**Issue by eworm-de** [NLnetLabs/ldns#252]
The [website](https://www.nlnetlabs.nl/projects/ldns/about/) lists version `1.8.3`, while the Github repository has version `1.8.4`.
What's the deal here?

**Comment by wcawijngaards** [comment]
Fixed it! If the page is still open in the browse a reload loads the new links. Also on the ldns download page the 1.8.4 release should show up.

**Comment by eworm-de** [comment]
Thanks a lot!
