### ISSUE TITLE
DNS over HTTPS in `drill`

### ISSUE THREAD

**Issue by eworm-de** [NLnetLabs/ldns#253]
The command `dig` from `bind` supports querying via *DNS over HTTPS* in later versions:
```
% dig example.com +https @1.1.1.1

; <<>> DiG 9.20.1 <<>> example.com +https @1.1.1.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6651
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;example.com.			IN	A

;; ANSWER SECTION:
example.com.		1114	IN	A	93.184.215.14

;; Query time: 13 msec
;; SERVER: 1.1.1.1#443(1.1.1.1) (HTTPS)
;; WHEN: Thu Sep 05 08:57:24 CEST 2024
;; MSG SIZE  rcvd: 56
```

Any chance to have that in `drill` as well?

**Comment by wtoorop** [comment]
> Any chance to have that in `drill` as well?

I don't think so, unless someone contributes it.  ldns is in maintenance mode (See development vision on https://nlnetlabs.nl/projects/ldns/about/ ). DoT, DoH and DoQ support for ldns would be quite involved.

NLnet Labs is actively developing on the rust [domain crate](https://github.com/NLnetLabs/domain) which will have all those features. The query tool using that library is called [dnsi](https://github.com/NLnetLabs/dnsi)

I _do_ have DNS over HTTPS on the shelve for getdns and will merge it in when I get to do a bugfix release for it.

**Comment by eworm-de** [comment]
Thanks a lot for answering. I will have an eye on `dnsi` then.
