### ISSUE TITLE
how to run program?

### ISSUE THREAD

**Issue by Phoenix1112** [NLnetLabs/ldns#45]
hello . i installed ldns . but i can't run

./configure && make

![Kazam_screenshot_00000](https://user-images.githubusercontent.com/42475284/62838110-6a7e2b00-bc80-11e9-865b-4981c2e660b6.png)

which of them starts the ldns-walk program?

**Comment by wcawijngaards** [comment]
User has closed it, but to note for others that look for a solution: the solution was to run the commands from README.git: `libtoolize -ci && autoreconf -fi` that creates the configure script.  `./configure --with-examples --with-drill` sets it up to create the example programs.  `--with-pyldns` for python.
