### ISSUE TITLE
Introduce +short option to drill

### ISSUE THREAD

**Issue by dilyanpalauzov** [NLnetLabs/ldns#56]
https://github.com/matteocorti/check_ssl_cert can if the TLSA records match the offered certificate (DANE) and can obtain the TLSA records using “dig +short” or “delv +short”.  To be able to use a different resolver, like “drill -D” or “drill -DT” that uses the same output/input format, please introduce option `+short` to drill.

**Comment by reedjc** [comment]
This is a duplicate of #28 .
