### ISSUE TITLE
OS X and Xcode assumptions

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/ldns#6]
Hi Everyone,

I'm working on an antique PowerMac running OS X 10.5 on a PowerPC. It is one of my favorite testing platforms. The 2.0 GHz processor is fast, and it still puts Intel Atoms and Celerons to shame. It offers OS X 10.5, Bash 3.2, GCC 4.0.1, Apple cc-tools linker, and big-endian PowerPC. I like to work on it so I often need to build newer tools like cURL, Git, SSH and Wget.

It looks like ldns is having some trouble on the PowerMac:

```
./libtool --tag=CC --quiet --mode=compile gcc -I. -I. -I/usr/local/include -DNDEBUG -DHAVE_CONFIG_H -DLDNS_TRUST_ANCHOR_FILE="\"/usr/local/etc/unbound/root.key\"" -Wunused-function -Wstrict-prototypes -Wwrite-strings -W -Wall -g2 -O2 -fPIC -pthread -mmacosx-version-min=10.10 -isysroot /Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I/usr/local/include -c ./buffer.c -o buffer.lo
<built-in>:1: error: Unknown value '10.10' of -mmacosx-version-min
In file included from ./buffer.c:10:
./ldns/config.h:508:19: error: stdio.h: No such file or directory
./ldns/config.h:509:20: error: string.h: No such file or directory
./ldns/config.h:510:20: error: unistd.h: No such file or directory
./ldns/config.h:511:20: error: assert.h: No such file or directory
./ldns/config.h:530:20: error: stdlib.h: No such file or directory
./ldns/config.h:531:20: error: stddef.h: No such file or directory
./ldns/config.h:535:20: error: stdint.h: No such file or directory
./ldns/config.h:539:24: error: sys/socket.h: No such file or directory
./ldns/config.h:543:24: error: netinet/in.h: No such file or directory
./ldns/config.h:547:23: error: arpa/inet.h: No such file or directory
```

I believe the issue is here in `configure.ac`:

```
# check OSX deployment target, if needed
if echo $build_os | grep darwin > /dev/null; then
  sdk_p=`xcode-select -print-path`;
  sdk_v="$( /usr/bin/xcrun --show-sdk-version )";
  case $sdk_v in
       10.9|10.8)   sdk_c="10.7";;
       10.11|10.10|*) sdk_c="10.10";;
  esac
  export MACOSX_DEPLOYMENT_TARGET="${sdk_c}";
  export CFLAGS="$CFLAGS -mmacosx-version-min=${sdk_c} -isysroot ${sdk_p}/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${sdk_v}.sdk";
fi
```

I believe the version of Xcode on the PowerMac is 2.5 or 3.1. It has been a while since I checked, and `xcrun` does not work like expected on the early versions:

```
checking whether the C compiler (gcc) accepts the "format" attribute... yes
checking whether the C compiler (gcc) accepts the "unused" attribute... yes
xcrun: error: unrecognized option: --show-sdk-version

usage:
xcrun [-verbose] [-no-cache] [-sdk <sdkroot>] [-log] [-run] <utility> [argument ...]
xcrun [-verbose] [-no-cache] [-sdk <sdkroot>] -find <utility>
<tool> [tool arguments ...]
configure: Default trust anchor: /usr/local/etc/unbound/root.key
configure: Using CAfile: /usr/local/etc/unbound/icannbundle.pem
configure: Using CApath: /usr/local/etc/unbound
configure: creating ./config.status
```

I think I am going to delete the Xcode block from `configure.ac` and use the regular build tools from CC Tools. (As opposed to the Xcode toolchain that is being used above).

You are welcomed to SSH access the box. I need your `authorized_keys`.

**Comment by noloader** [comment]
OK, good news. This patched tested fine on OS X 10.5: [Commit 09efa41ab472](https://github.com/noloader/Build-Scripts/commit/09efa41ab472).

It looks like a good strategy for ldns is, avoid Xcode for OS X 10.1 - 10.7. It may be a good strategy overall since everything I am building uses GCC/Clang from CC Tools; and not the Xcode SDKs. So maybe `configure` needs a switch like `--with-xcode-sdk` to enable XCode builds.

That's great because it means we can build OpenSSH with DNSSEC report on the old machine.

**Comment by wtoorop** [comment]
I'm happy you're happy :).

 Though I'd prefer something that would not change old behaviour. So perhaps a `--without-xcode-sdk` option? (so `--with-xcode-sdk=10.10` would set it explicitly and leaving the default value (`yes`?) would perform the kind of scanning we did before...)  WDYT?

**Comment by noloader** [comment]
> So perhaps a --without-xcode-sdk option? (so --with-xcode-sdk=10.10 would set it explicitly and leaving the default value (yes?) would perform the kind of scanning we did before...)

Sounds good to me.

**Comment by wtoorop** [comment]
Thanks, this is now in develop
