### ISSUE TITLE
ldns build fails with SWIG 4.0.0

### ISSUE THREAD

**Issue by jplesnik** [NLnetLabs/ldns#7]
SWIG was updated to version 4.0.0 in Fedora Rawhide. 
Then I tried to rebuild ldns with this version and it failed. I reported it to [upstream](https://sourceforge.net/p/swig/mailman/message/36590176/) and they recommended me the [solution](https://sourceforge.net/p/swig/mailman/message/36590978/).

I created the [patch](https://jplesnik.fedorapeople.org/swig-4/ldns/ldns-1.7.0-Update-for-SWIG-4.patch) which will be applied in Fedora and solve the issue.

**Comment by wtoorop** [comment]
Thanks!
Merged with pr #23
