### ISSUE TITLE
Build android ldns library with ndk-r20b

### ISSUE THREAD

**Issue by czlitony** [NLnetLabs/ldns#77]
At before, we use ndk-r17c to build ldns for android. In ndk-r17c toolchain, there is gcc tool for cross-compiling. Now we decide to upgrade ndk to ndk-r20b, however there is no gcc in ndk-r20b, so I am wondering how to builld ldns for android with ndk-r20b?

**Comment by noloader** [comment]
@czlitony,

See PR 87, [Add Android to Travis testing](https://github.com/NLnetLabs/ldns/pull/87). The PR adds Android testing using NDK-r20 and Android API 23. There is also a `README-Travis.md` that explains what is happening.

**Comment by noloader** [comment]
@czlitony,

The PR was merged. Now see [Commit 895147b81d94](https://github.com/NLnetLabs/ldns/commit/895147b81d94).

**Comment by noloader** [comment]
@czlitony,

The PR was merged. Now see [Commit 895147b81d94](https://github.com/NLnetLabs/ldns/commit/895147b81d94).

**Comment by czlitony** [comment]
> @czlitony,
> 
> The PR was merged. Now see [Commit 895147b81d94](https://github.com/NLnetLabs/ldns/commit/895147b81d94).

@noloader Thank you very much, I can build ldns with ndk-r20 now. When will this be released?  If I merge the commit  895147b81d94 to 1.7.1 branch, then I can build ldns-1.7.1 with ndk-r20, right?

**Comment by noloader** [comment]
@czlitony,

>  If I merge the commit 895147b to 1.7.1 branch, then I can build ldns-1.7.1 with ndk-r20, right?

I'm sorry, I am not sure.

Ping @wcawijngaards, @wtoorop.

**Comment by wtoorop** [comment]
Resolved in ldns-1.8.0 release
