### ISSUE TITLE
'make test' fails due to missing test/test_all.sh

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/ldns#8]
Hi Everyone,

I'm testing ldns 1.7.0 from the release tarball. `make` builds the library OK. `make test` is failing after the build:

```
make test
...

if test -x "`which bash`"; then bash test/test_all.sh; else sh test/test_all.sh; fi
bash: test/test_all.sh: No such file or directory
gmake: *** [Makefile:461: test] Error 127
```

Maybe that test should be `[ -f test/test_all.sh]` or don't try the self tests.

**Comment by wtoorop** [comment]
Acknowledged @noloader ,

The release tarballs do intentionally not include the unit tests (and a lot of other stuff we do not ship with the release), but does still have the test target in the Makefile.  I'll remove the test target and start unit tests from a .travis.yml file...

**Comment by noloader** [comment]
How do I test the build?

Specifically, I'm trying to perform Sanitizer testing using UBsan and Asan.

**Comment by wtoorop** [comment]
You can run the tests when checking out the source repository
