### ISSUE TITLE
ldns_rdf2buffer_str_wks never return when WKS record includes port number 65528 or higher

### ISSUE THREAD

**Issue by yuuki-w** [NLnetLabs/ldns#95]
When a WKS record has services which port number is over 65528, ldns_rdf2buffer_str_wks never return.

In host2str.c:841 (in 1.7.1)
```
 822     uint16_t current_service;
// ...
 840     for (current_service = 0;
 841          current_service < (ldns_rdf_size(rdf)-1)*8; current_service++) {
```
In this case, `(ldns_rdf_size(rdf)-1)* 8` is 65536 but the variable `current_service` is uint16_t so overflows after checking port 65535, the condition never become false.

**Comment by wtoorop** [comment]
Perfect. Thanks!

**Comment by wtoorop** [comment]
I mean good catch :).  The perfect is for PR #96
